### PR TITLE
massive dependency cleanup

### PR DESCRIPTION
**Pull request by davidmsibley**

### CODE REVIEW

**Comment by davidmsibley** [comment]
@isuftin @thongsav-usgs

**Comment by isuftin** [comment]
:ok:  This looks good. Have you given this a good integration test:question:

**Comment by thongsav-usgs** [comment]
Looks good to me

**Comment by davidmsibley** [comment]
no :bangbang:  I've run unit tests but no integration tests.  I'll run them.  I expect them to be :hankey:

**Comment by davidmsibley** [comment]
yep, I broke integration tests.  I'll fix that.

**Pull request merged**
