### PR TITLE
AQCU-1341: raise timeout to 10 minutes from 1 minute

### PR DESCRIPTION
**Pull request by mhines-usgs**
This expires very quickly and then fails badly when it's expired. first part of fix, extend timeout to 10 mins.

### CODE REVIEW

**Comment by isuftin** [comment]
@mhines-usgs  You may want to update the comment to the right of that change

**Comment by mhines-usgs** [comment]
@isuftin / others -- do you think it's worth pushing this out, while we address this issue in a more intelligent way? just so that users can get past it?

**Comment by isuftin** [comment]
I'd suggest that it wouldn't hurt to do so. Redeploying should be quick/easy. Probable downtime should be about 1 minute

**Comment by mhines-usgs** [comment]
Shall we, then?

**Comment by mhines-usgs** [comment]
I can ask Kris/Laura/Chuck for a blessing

**Pull request merged**
